
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def sleep_ms(t: Any) -> None: ...
def sleep_us(t: Any) -> None: ...
def ticks_ms() -> Any: ...
    #   0: return int(time.time()*)&MICROPY_PY_UTIME_TICKS_PERIOD-
    # ? 0: return int&MICROPY_PY_UTIME_TICKS_PERIOD-
def ticks_us() -> Any: ...
    #   0: return int(time.time()*)&MICROPY_PY_UTIME_TICKS_PERIOD-
    # ? 0: return int&MICROPY_PY_UTIME_TICKS_PERIOD-
